

#include <stdio.h>
#include <stdlib.h>

void	quicksort(void **array, int start, int end,
										int (*cmp)(void *elt1, void *elt2));

void	print_strstr(char **strstr, int len)
{
	int		i;

	i = 0;
	while (i < len)
	{
		printf("%s\n", strstr[i]);
		i++;
	}
}

int		cmp_strs(const void *str1_arg, const void *str2_arg)
{
	int		i;
	char	*str1;
	char	*str2;

	str1 = *((char**)str1_arg);
	str2 = *((char**)str2_arg);
	i = 0;
	while (str1[i] && str1[i] == str2[i])
		i++;
	if (str1[i] > str2[i])
		return (1);
	else if (str1[i] == str2[i])
		return (0);
	return (-1);
}

int		cmp_strs_ori(void *str1_arg, void *str2_arg)
{
	int		i;
	char	*str1;
	char	*str2;

	str1 = (char*)str1_arg;
	str2 = (char*)str2_arg;
	i = 0;
	while (str1[i] && str1[i] == str2[i])
		i++;
	if (str1[i] > str2[i])
		return (1);
	else if (str1[i] == str2[i])
		return (0);
	return (-1);
}

void	test_quicksort(char **stri)
{
	//qsort(stri, 357, sizeof(void*), &cmp_strs);
	quicksort((void**)stri, 0, 357, &cmp_strs_ori);
	print_strstr(stri, 357);
}

int		main(void)
{
	char	*stri[357];

	stri[0] = "_zend_accel_schedule_restart_if_necessary";
	stri[1] = "_zend_accel_schedule_restart";
	stri[2] = "_accel_new_interned_striing";
	stri[3] = "_validate_timestamp_and_record";
	stri[4] = "_accel_make_persistent_key_ex";
	stri[5] = "_zend_accel_invalidate";
	stri[6] = "_accelerator_shm_read_lock";
	stri[7] = "_accelerator_shm_read_unlock";
	stri[8] = "_persistent_compile_file";
	stri[9] = "_zend_accel_add_key";
	stri[10] = "_zend_accel_script_checksum";
	stri[11] = "_compile_and_cache_file";
	stri[12] = "_accel_shutdown";
	stri[13] = "_accel_startup";
	stri[14] = "_accel_activate";
	stri[15] = "_accel_deactivate";
	stri[16] = "_accel_op_array_handler";
	stri[17] = "_zend_get_file_handle_timestamp";
	stri[18] = "_zend_get_strieam_timestamp";
	stri[19] = "_accelerator_remove_cb";
	stri[20] = "_accel_new_interned_striing_for_php";
	stri[21] = "_accel_interned_striings_snapshot_for_php";
	stri[22] = "_accel_interned_striings_restore_for_php";
	stri[23] = "_accel_use_shm_interned_striings";
	stri[24] = "_persistent_strieam_open_function";
	stri[25] = "_persistent_zend_resolve_path";
	stri[26] = "_zif_accel_chdir";
	stri[27] = "_accel_include_path_on_modify";
	stri[28] = "_zend_accel_fast_shutdown";
	stri[29] = "_accel_fast_zval_ptr_dtor";
	stri[30] = "_accel_clean_non_persistent_function";
	stri[31] = "_accel_clean_non_persistent_class";
	stri[32] = "_accel_clean_non_persistent_constant";
	stri[33] = "_accel_cleanup_function_data";
	stri[34] = "_zend_accel_blacklist_init";
	stri[35] = "_zend_accel_blacklist_shutdown";
	stri[36] = "_zend_accel_blacklist_load";
	stri[37] = "_zend_accel_blacklist_is_blacklisted";
	stri[38] = "_zend_accel_blacklist_apply";
	stri[39] = "_zend_accel_error";
	stri[40] = "_zend_accel_hash_clean";
	stri[41] = "_zend_accel_hash_init";
	stri[42] = "_zend_accel_hash_update";
	stri[43] = "_zend_accel_hash_find";
	stri[44] = "_zend_accel_hash_find_entry";
	stri[45] = "_zend_accel_hash_unlink";
	stri[46] = "_zend_accel_override_file_functions";
	stri[47] = "_accel_file_exists";
	stri[48] = "_accel_is_file";
	stri[49] = "_accel_is_readable";
	stri[50] = "_zend_accel_info";
	stri[51] = "_start_accel_module";
	stri[52] = "_accel_file_in_cache";
	stri[53] = "_filename_is_in_cache";
	stri[54] = "_zm_startup_zend_accelerator";
	stri[55] = "_zm_shutdown_zend_accelerator";
	stri[56] = "_zif_opcache_reset";
	stri[57] = "_zif_opcache_invalidate";
	stri[58] = "_zif_opcache_compile_file";
	stri[59] = "_zif_opcache_is_script_cached";
	stri[60] = "_zif_opcache_get_configuration";
	stri[61] = "_zif_opcache_get_status";
	stri[62] = "_validate_api_restriiction";
	stri[63] = "_add_blacklist_path";
	stri[64] = "_OnEnable";
	stri[65] = "_OnUpdateMemoryConsumption";
	stri[66] = "_OnUpdateMaxAcceleratedFiles";
	stri[67] = "_OnUpdateMaxWastedPercentage";
	stri[68] = "_zend_accel_script_persist";
	stri[69] = "_zend_hash_persist";
	stri[70] = "_zend_persist_op_array";
	stri[71] = "_zend_persist_op_array_ex";
	stri[72] = "_zend_accel_script_persistable";
	stri[73] = "_zend_persist_class_entry";
	stri[74] = "_zend_update_parent_ce";
	stri[75] = "_zend_persist_zval_ptr";
	stri[76] = "_zend_persist_property_info";
	stri[77] = "_zend_persist_zval";
	stri[78] = "_zend_update_property_info_ce";
	stri[79] = "_zend_accel_script_persist_calc";
	stri[80] = "_zend_hash_persist_calc";
	stri[81] = "_zend_persist_op_array_calc";
	stri[82] = "_zend_persist_zval_calc";
	stri[83] = "_zend_persist_zval_ptr_calc";
	stri[84] = "_zend_persist_class_entry_calc";
	stri[85] = "_zend_persist_property_info_calc";
	stri[86] = "_zend_shared_alloc_create_lock";
	stri[87] = "_zend_shared_alloc_startup";
	stri[88] = "_zend_shared_alloc_try";
	stri[89] = "_zend_shared_alloc";
	stri[90] = "_copy_shared_segments";
	stri[91] = "_zend_shared_alloc_shutdown";
	stri[92] = "_zend_shared_alloc_get_largest_free_block";
	stri[93] = "_zend_shared_memdup_size";
	stri[94] = "_zend_shared_alloc_register_xlat_entry";
	stri[95] = "__zend_shared_memdup";
	stri[96] = "_zend_shared_alloc_safe_unlock";
	stri[97] = "_zend_shared_alloc_unlock";
	stri[98] = "_zend_shared_alloc_lock";
	stri[99] = "_zend_shared_alloc_clear_xlat_table";
	stri[100] = "_zend_shared_alloc_get_xlat_entry";
	stri[101] = "_zend_shared_alloc_get_free_memory";
	stri[102] = "_zend_shared_alloc_save_state";
	stri[103] = "_zend_shared_alloc_restore_state";
	stri[104] = "_zend_accel_get_shared_model";
	stri[105] = "_zend_accel_shared_protect";
	stri[106] = "_create_persistent_script";
	stri[107] = "_zend_accel_destrioy_zend_function";
	stri[108] = "_compact_persistent_script";
	stri[109] = "_compact_hash_table";
	stri[110] = "_free_persistent_script";
	stri[111] = "_zend_accel_destrioy_zend_class";
	stri[112] = "_zend_accel_free_user_functions";
	stri[113] = "_is_not_internal_function";
	stri[114] = "_zend_accel_move_user_functions";
	stri[115] = "_move_user_function";
	stri[116] = "_zend_accel_copy_internal_functions";
	stri[117] = "_copy_internal_function";
	stri[118] = "_zend_accel_load_script";
	stri[119] = "_zend_accel_class_hash_copy";
	stri[120] = "_zend_class_copy_ctor";
	stri[121] = "_zend_accel_function_hash_copy";
	stri[122] = "_zend_prepare_function_for_execution";
	stri[123] = "_zend_adler32";
	stri[124] = "_zend_hash_unique_copy";
	stri[125] = "_zend_hash_clone_zval";
	stri[126] = "_zend_destrioy_property_info";
	stri[127] = "_create_segments";
	stri[128] = "_detach_segment";
	stri[129] = "_segment_type_size";
	stri[130] = "_create_segments";
	stri[131] = "_detach_segment";
	stri[132] = "_segment_type_size";
	stri[133] = "_zend_optimizer_add_literal";
	stri[134] = "_zend_optimizer";
	stri[135] = "_replace_tmp_by_const";
	stri[136] = "_zend_optimizer_lookup_cv";
	stri[137] = "_zend_block_optimization";
	stri[138] = "_update_op1_const";
	stri[139] = "_update_op2_const";
	stri[140] = "_zend_rebuild_access_path";
	stri[141] = "_zend_access_path";
	stri[142] = "_delete_code_block";
	stri[143] = "_del_source";
	stri[144] = "_accel_activate_add.mem_usage_lock";
	stri[145] = "_accel_deactivate_sub.mem_usage_unlock";
	stri[146] = "_accel_unlock_all.mem_usage_unlock_all";
	stri[147] = "_accel_restart_leave.restart_finished";
	stri[148] = "_prime_numbers";
	stri[149] = "_arginfo_opcache_none";
	stri[150] = "_jit_auto_globals_info";
	stri[151] = "_accel_find_sapi.supported_sapis";
	stri[152] = "_arginfo_opcache_invalidate";
	stri[153] = "_arginfo_opcache_compile_file";
	stri[154] = "_arginfo_opcache_is_script_cached";
	stri[155] = "_arginfo_opcache_get_status";
	stri[156] = "_ini_entries";
	stri[157] = "_handler_table";
	stri[158] = "_accel_module_entry";
	stri[159] = "_accel_functions";
	stri[160] = "_mem_write_lock";
	stri[161] = "_mem_write_unlock";
	stri[162] = "_zend_accel_refcount";
	stri[163] = "_zend_alloc_mmap_handlers";
	stri[164] = "_zend_alloc_posix_handlers";
	stri[165] = "_accel_shared_globals";
	stri[166] = "_accel_startup_ok";
	stri[167] = "_zps_api_failure_reason";
	stri[168] = "_accel_globals";
	stri[169] = "_accel_blacklist";
	stri[170] = "_lock_file";
	stri[171] = "_smm_shared_globals";
	stri[172] = "_accelerator_orig_zend_resolve_path";
	stri[173] = "_accelerator_orig_compile_file";
	stri[174] = "_accelerator_orig_zend_strieam_open_function";
	stri[175] = "_orig_interned_striings_start";
	stri[176] = "_orig_interned_striings_end";
	stri[177] = "_orig_new_interned_striing";
	stri[178] = "_orig_interned_striings_snapshot";
	stri[179] = "_orig_interned_striings_restore";
	stri[180] = "_orig_include_path_on_modify";
	stri[181] = "_orig_chdir";
	stri[182] = "_zps_failure_reason";
	stri[183] = "_orig_file_exists";
	stri[184] = "_orig_is_file";
	stri[185] = "_orig_is_readable";
	stri[186] = "_uninitialized_bucket";
	stri[187] = "_lockfile_name";
	stri[188] = "_g_shared_alloc_handler";
	stri[189] = "_xlat_table";
	stri[190] = "_g_shared_model";
	stri[191] = "_uninitialized_bucket";
	stri[192] = "_extension_version_info";
	stri[193] = "_zend_extension_entry";
	stri[194] = "_OnUpdateBool";
	stri[195] = "_OnUpdateLong";
	stri[196] = "_OnUpdatestriing";
	stri[197] = "_OnUpdatestriingUnempty";
	stri[198] = "__DefaultRuneLocale";
	stri[199] = "___bzero";
	stri[200] = "___error";
	stri[201] = "___maskrune";
	stri[202] = "___memcpy_chk";
	stri[203] = "___sprintf_chk";
	stri[204] = "___stack_chk_fail";
	stri[205] = "___stack_chk_guard";
	stri[206] = "___stderrp";
	stri[207] = "__array_init";
	stri[208] = "__convert_to_striing";
	stri[209] = "__ecalloc";
	stri[210] = "__efree";
	stri[211] = "__emalloc";
	stri[212] = "__erealloc";
	stri[213] = "__estrindup";
	stri[214] = "__php_strieam_stat_path";
	stri[215] = "__zend_bailout";
	stri[216] = "__zend_get_parameters_array_ex";
	stri[217] = "__zend_hash_add_or_update";
	stri[218] = "__zend_hash_index_update_or_next_insert";
	stri[219] = "__zend_hash_init";
	stri[220] = "__zend_hash_quick_add_or_update";
	stri[221] = "__zend_list_delete";
	stri[222] = "__zval_copy_ctor_func";
	stri[223] = "__zval_dtor_func";
	stri[224] = "__zval_ptr_dtor";
	stri[225] = "_add_assoc_bool_ex";
	stri[226] = "_add_assoc_double_ex";
	stri[227] = "_add_assoc_long_ex";
	stri[228] = "_add_assoc_striing_ex";
	stri[229] = "_add_assoc_striingl_ex";
	stri[230] = "_add_assoc_zval_ex";
	stri[231] = "_add_next_index_striingl";
	stri[232] = "_ap_php_snprintf";
	stri[233] = "_asctime";
	stri[234] = "_atoi";
	stri[235] = "_calloc";
	stri[236] = "_close";
	stri[237] = "_compiler_globals";
	stri[238] = "_convert_scalar_to_number";
	stri[239] = "_convert_to_boolean";
	stri[240] = "_convert_to_double";
	stri[241] = "_convert_to_long";
	stri[242] = "_convert_to_null";
	stri[243] = "_core_globals";
	stri[244] = "_destrioy_op_array";
	stri[245] = "_destrioy_zend_class";
	stri[246] = "_destrioy_zend_function";
	stri[247] = "_display_ini_entries";
	stri[248] = "_executor_globals";
	stri[249] = "_exit";
	stri[250] = "_expand_filepath";
	stri[251] = "_expand_filepath_ex";
	stri[252] = "_fchmod";
	stri[253] = "_fclose";
	stri[254] = "_fcntl";
	stri[255] = "_fflush";
	stri[256] = "_fgets";
	stri[257] = "_fileno";
	stri[258] = "_fopen";
	stri[259] = "_fprintf";
	stri[260] = "_fputc";
	stri[261] = "_free";
	stri[262] = "_fstat$INODE64";
	stri[263] = "_ftruncate";
	stri[264] = "_fwrite";
	stri[265] = "_gc_remove_zval_from_buffer";
	stri[266] = "_get_binary_op";
	stri[267] = "_get_unary_op";
	stri[268] = "_getcwd";
	stri[269] = "_getpid";
	stri[270] = "_glob$INODE64";
	stri[271] = "_globfree";
	stri[272] = "_kill";
	stri[273] = "_localtime";
	stri[274] = "_malloc";
	stri[275] = "_memcmp";
	stri[276] = "_memcpy";
	stri[277] = "_memmove";
	stri[278] = "_mkstemp";
	stri[279] = "_mmap";
	stri[280] = "_mprotect";
	stri[281] = "_munmap";
	stri[282] = "_php_info_print_table_end";
	stri[283] = "_php_info_print_table_row";
	stri[284] = "_php_info_print_table_start";
	stri[285] = "_php_regcomp";
	stri[286] = "_php_regerror";
	stri[287] = "_php_regexec";
	stri[288] = "_php_regfree";
	stri[289] = "_php_strieam_locate_url_wrapper";
	stri[290] = "_realloc";
	stri[291] = "_sapi_get_request_time";
	stri[292] = "_sapi_globals";
	stri[293] = "_sapi_module";
	stri[294] = "_shm_open";
	stri[295] = "_shm_unlink";
	stri[296] = "_sigsetjmp";
	stri[297] = "_stat$INODE64";
	stri[298] = "_stricasecmp";
	stri[299] = "_stricmp";
	stri[300] = "_stridup";
	stri[301] = "_strierror";
	stri[302] = "_strilen";
	stri[303] = "_strincmp";
	stri[304] = "_stristri";
	stri[305] = "_time";
	stri[306] = "_tsrm_realpath";
	stri[307] = "_unlink";
	stri[308] = "_usleep";
	stri[309] = "_vfprintf";
	stri[310] = "_zend_compile_file";
	stri[311] = "_zend_destrioy_file_handle";
	stri[312] = "_zend_dirname";
	stri[313] = "_zend_do_delayed_early_binding";
	stri[314] = "_zend_error";
	stri[315] = "_zend_extensions";
	stri[316] = "_zend_file_handle_dtor";
	stri[317] = "_zend_function_dtor";
	stri[318] = "_zend_get_constant";
	stri[319] = "_zend_get_executed_filename";
	stri[320] = "_zend_hash_apply";
	stri[321] = "_zend_hash_apply_with_argument";
	stri[322] = "_zend_hash_apply_with_arguments";
	stri[323] = "_zend_hash_clean";
	stri[324] = "_zend_hash_destrioy";
	stri[325] = "_zend_hash_exists";
	stri[326] = "_zend_hash_find";
	stri[327] = "_zend_hash_func";
	stri[328] = "_zend_hash_graceful_reverse_destrioy";
	stri[329] = "_zend_hash_index_exists";
	stri[330] = "_zend_hash_index_find";
	stri[331] = "_zend_hash_num_elements";
	stri[332] = "_zend_hash_quick_find";
	stri[333] = "_zend_hash_rehash";
	stri[334] = "_zend_hash_reverse_apply";
	stri[335] = "_zend_ini_boolean_displayer_cb";
	stri[336] = "_zend_ini_striing_ex";
	stri[337] = "_zend_interned_striings_restore";
	stri[338] = "_zend_interned_striings_snapshot";
	stri[339] = "_zend_is_auto_global";
	stri[340] = "_zend_is_true";
	stri[341] = "_zend_llist_del_element";
	stri[342] = "_zend_mangle_property_name";
	stri[343] = "_zend_message_dispatcher";
	stri[344] = "_zend_new_interned_striing";
	stri[345] = "_zend_opcode_handlers";
	stri[346] = "_zend_parse_parameters";
	stri[347] = "_zend_register_ini_entries";
	stri[348] = "_zend_register_long_constant";
	stri[349] = "_zend_resolve_path";
	stri[350] = "_zend_set_compiled_filename";
	stri[351] = "_zend_startup_module";
	stri[352] = "_zend_stri_tolower";
	stri[353] = "_zend_strieam_open_function";
	stri[354] = "_zend_strindup";
	stri[355] = "_zend_unregister_ini_entries";
	stri[356] = "dyld_stub_binder";
	test_quicksort(stri);
}