RESULT = molecule
SOURCES = atom.ml bohrium.ml cadmium.ml carbon.ml helium.ml hydrogen.ml nitrogen.ml oxygen.ml yttrium.ml sulphur.ml molecule.ml carbon_dioxyde.ml water.ml trinitrotoluene.ml biotin.ml leucine.ml main.ml
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
